import { ExerciseCategory } from '../utils/calculations';

export interface DefaultExercise {
  name: string;
  category: ExerciseCategory;
  muscle_groups: string[];
  equipment: string[];
}

/**
 * Same catalog migration 016 seeded retroactively for every user that
 * existed at the time — that migration is a one-time INSERT and never runs
 * again, so anyone who signed up afterward got zero exercises and had to
 * create every single one by hand before logging their first set. Seeded
 * again here, at first-login provisioning, so new accounts start with the
 * same starting library instead of an empty one.
 */
export const DEFAULT_EXERCISE_CATALOG: DefaultExercise[] = [
  { name: 'Press banca', category: 'compound', muscle_groups: ['Pecho'], equipment: ['Barra'] },
  { name: 'Press banca inclinado', category: 'compound', muscle_groups: ['Pecho'], equipment: ['Barra'] },
  { name: 'Press banca declinado', category: 'compound', muscle_groups: ['Pecho'], equipment: ['Barra'] },
  { name: 'Press banca con mancuernas', category: 'compound', muscle_groups: ['Pecho'], equipment: ['Mancuerna'] },
  { name: 'Press inclinado con mancuernas', category: 'compound', muscle_groups: ['Pecho'], equipment: ['Mancuerna'] },
  { name: 'Press declinado con mancuernas', category: 'compound', muscle_groups: ['Pecho'], equipment: ['Mancuerna'] },
  { name: 'Aperturas con mancuernas', category: 'isolation', muscle_groups: ['Pecho'], equipment: ['Mancuerna'] },
  { name: 'Aperturas en cable', category: 'isolation', muscle_groups: ['Pecho'], equipment: ['Cable'] },
  { name: 'Fondos en paralelas', category: 'compound', muscle_groups: ['Pecho', 'Tríceps'], equipment: ['Peso corporal'] },
  { name: 'Press en máquina', category: 'compound', muscle_groups: ['Pecho'], equipment: ['Máquina'] },
  { name: 'Pec deck (contractora)', category: 'isolation', muscle_groups: ['Pecho'], equipment: ['Máquina'] },
  { name: 'Flexiones', category: 'compound', muscle_groups: ['Pecho', 'Tríceps'], equipment: ['Peso corporal'] },
  { name: 'Cruce de poleas', category: 'isolation', muscle_groups: ['Pecho'], equipment: ['Cable'] },
  { name: 'Press banca con agarre cerrado', category: 'compound', muscle_groups: ['Pecho', 'Tríceps'], equipment: ['Barra'] },
  { name: 'Dominadas', category: 'compound', muscle_groups: ['Espalda', 'Bíceps'], equipment: ['Peso corporal'] },
  { name: 'Dominadas asistidas', category: 'compound', muscle_groups: ['Espalda', 'Bíceps'], equipment: ['Máquina'] },
  { name: 'Dominadas supinas', category: 'compound', muscle_groups: ['Espalda', 'Bíceps'], equipment: ['Peso corporal'] },
  { name: 'Remo con barra', category: 'compound', muscle_groups: ['Espalda'], equipment: ['Barra'] },
  { name: 'Remo con mancuerna a una mano', category: 'compound', muscle_groups: ['Espalda'], equipment: ['Mancuerna'] },
  { name: 'Remo en máquina sentado', category: 'compound', muscle_groups: ['Espalda'], equipment: ['Máquina'] },
  { name: 'Remo en cable sentado', category: 'compound', muscle_groups: ['Espalda'], equipment: ['Cable'] },
  { name: 'Remo en T', category: 'compound', muscle_groups: ['Espalda'], equipment: ['Barra'] },
  { name: 'Jalón al pecho', category: 'compound', muscle_groups: ['Espalda', 'Bíceps'], equipment: ['Cable'] },
  { name: 'Jalón tras nuca', category: 'compound', muscle_groups: ['Espalda'], equipment: ['Cable'] },
  { name: 'Peso muerto', category: 'compound', muscle_groups: ['Espalda', 'Piernas', 'Glúteos'], equipment: ['Barra'] },
  { name: 'Peso muerto rumano', category: 'compound', muscle_groups: ['Espalda', 'Piernas', 'Glúteos'], equipment: ['Barra'] },
  { name: 'Peso muerto sumo', category: 'compound', muscle_groups: ['Espalda', 'Piernas', 'Glúteos'], equipment: ['Barra'] },
  { name: 'Peso muerto con mancuernas', category: 'compound', muscle_groups: ['Espalda', 'Piernas', 'Glúteos'], equipment: ['Mancuerna'] },
  { name: 'Face pull', category: 'isolation', muscle_groups: ['Espalda', 'Hombros'], equipment: ['Cable'] },
  { name: 'Pull-over con mancuerna', category: 'isolation', muscle_groups: ['Espalda', 'Pecho'], equipment: ['Mancuerna'] },
  { name: 'Hiperextensiones', category: 'isolation', muscle_groups: ['Espalda', 'Glúteos'], equipment: ['Peso corporal'] },
  { name: 'Buenos días', category: 'compound', muscle_groups: ['Espalda', 'Piernas'], equipment: ['Barra'] },
  { name: 'Sentadilla', category: 'compound', muscle_groups: ['Piernas', 'Glúteos'], equipment: ['Barra'] },
  { name: 'Sentadilla frontal', category: 'compound', muscle_groups: ['Piernas'], equipment: ['Barra'] },
  { name: 'Sentadilla búlgara', category: 'compound', muscle_groups: ['Piernas', 'Glúteos'], equipment: ['Mancuerna'] },
  { name: 'Sentadilla goblet', category: 'compound', muscle_groups: ['Piernas', 'Glúteos'], equipment: ['Mancuerna'] },
  { name: 'Sentadilla hack', category: 'compound', muscle_groups: ['Piernas'], equipment: ['Máquina'] },
  { name: 'Prensa de piernas', category: 'compound', muscle_groups: ['Piernas', 'Glúteos'], equipment: ['Máquina'] },
  { name: 'Zancadas', category: 'compound', muscle_groups: ['Piernas', 'Glúteos'], equipment: ['Mancuerna'] },
  { name: 'Zancadas caminando', category: 'compound', muscle_groups: ['Piernas', 'Glúteos'], equipment: ['Mancuerna'] },
  { name: 'Extensión de cuádriceps', category: 'isolation', muscle_groups: ['Piernas'], equipment: ['Máquina'] },
  { name: 'Curl femoral tumbado', category: 'isolation', muscle_groups: ['Piernas'], equipment: ['Máquina'] },
  { name: 'Curl femoral sentado', category: 'isolation', muscle_groups: ['Piernas'], equipment: ['Máquina'] },
  { name: 'Peso muerto a piernas rígidas', category: 'compound', muscle_groups: ['Piernas', 'Glúteos'], equipment: ['Barra'] },
  { name: 'Step-up', category: 'compound', muscle_groups: ['Piernas', 'Glúteos'], equipment: ['Mancuerna'] },
  { name: 'Abducción de cadera en máquina', category: 'isolation', muscle_groups: ['Glúteos'], equipment: ['Máquina'] },
  { name: 'Aducción de cadera en máquina', category: 'isolation', muscle_groups: ['Piernas'], equipment: ['Máquina'] },
  { name: 'Sentadilla pistol', category: 'compound', muscle_groups: ['Piernas', 'Glúteos'], equipment: ['Peso corporal'] },
  { name: 'Hip thrust', category: 'compound', muscle_groups: ['Glúteos'], equipment: ['Barra'] },
  { name: 'Puente de glúteo', category: 'isolation', muscle_groups: ['Glúteos'], equipment: ['Peso corporal'] },
  { name: 'Patada de glúteo en cable', category: 'isolation', muscle_groups: ['Glúteos'], equipment: ['Cable'] },
  { name: 'Patada de glúteo en máquina', category: 'isolation', muscle_groups: ['Glúteos'], equipment: ['Máquina'] },
  { name: 'Press militar', category: 'compound', muscle_groups: ['Hombros'], equipment: ['Barra'] },
  { name: 'Press militar con mancuernas', category: 'compound', muscle_groups: ['Hombros'], equipment: ['Mancuerna'] },
  { name: 'Press Arnold', category: 'compound', muscle_groups: ['Hombros'], equipment: ['Mancuerna'] },
  { name: 'Press tras nuca', category: 'compound', muscle_groups: ['Hombros'], equipment: ['Barra'] },
  { name: 'Press de hombros en máquina', category: 'compound', muscle_groups: ['Hombros'], equipment: ['Máquina'] },
  { name: 'Elevaciones laterales', category: 'isolation', muscle_groups: ['Hombros'], equipment: ['Mancuerna'] },
  { name: 'Elevaciones laterales en cable', category: 'isolation', muscle_groups: ['Hombros'], equipment: ['Cable'] },
  { name: 'Elevaciones frontales', category: 'isolation', muscle_groups: ['Hombros'], equipment: ['Mancuerna'] },
  { name: 'Pájaros (elevaciones posteriores)', category: 'isolation', muscle_groups: ['Hombros'], equipment: ['Mancuerna'] },
  { name: 'Pájaros en máquina', category: 'isolation', muscle_groups: ['Hombros'], equipment: ['Máquina'] },
  { name: 'Remo al mentón', category: 'compound', muscle_groups: ['Hombros'], equipment: ['Barra'] },
  { name: 'Encogimientos de hombros', category: 'isolation', muscle_groups: ['Hombros'], equipment: ['Mancuerna'] },
  { name: 'Curl con barra', category: 'isolation', muscle_groups: ['Bíceps'], equipment: ['Barra'] },
  { name: 'Curl con barra Z', category: 'isolation', muscle_groups: ['Bíceps'], equipment: ['Barra'] },
  { name: 'Curl con mancuernas', category: 'isolation', muscle_groups: ['Bíceps'], equipment: ['Mancuerna'] },
  { name: 'Curl martillo', category: 'isolation', muscle_groups: ['Bíceps', 'Antebrazos'], equipment: ['Mancuerna'] },
  { name: 'Curl concentrado', category: 'isolation', muscle_groups: ['Bíceps'], equipment: ['Mancuerna'] },
  { name: 'Curl en banco Scott', category: 'isolation', muscle_groups: ['Bíceps'], equipment: ['Barra'] },
  { name: 'Curl en polea', category: 'isolation', muscle_groups: ['Bíceps'], equipment: ['Cable'] },
  { name: 'Curl inclinado con mancuernas', category: 'isolation', muscle_groups: ['Bíceps'], equipment: ['Mancuerna'] },
  { name: 'Press francés', category: 'isolation', muscle_groups: ['Tríceps'], equipment: ['Barra'] },
  { name: 'Extensión de tríceps en polea', category: 'isolation', muscle_groups: ['Tríceps'], equipment: ['Cable'] },
  { name: 'Extensión de tríceps con cuerda', category: 'isolation', muscle_groups: ['Tríceps'], equipment: ['Cable'] },
  { name: 'Fondos entre bancos', category: 'compound', muscle_groups: ['Tríceps'], equipment: ['Peso corporal'] },
  { name: 'Patada de tríceps', category: 'isolation', muscle_groups: ['Tríceps'], equipment: ['Mancuerna'] },
  { name: 'Extensión de tríceps sobre la cabeza', category: 'isolation', muscle_groups: ['Tríceps'], equipment: ['Mancuerna'] },
  { name: 'Press cerrado en banca', category: 'compound', muscle_groups: ['Tríceps', 'Pecho'], equipment: ['Barra'] },
  { name: 'Plancha', category: 'isolation', muscle_groups: ['Core'], equipment: ['Peso corporal'] },
  { name: 'Plancha lateral', category: 'isolation', muscle_groups: ['Core'], equipment: ['Peso corporal'] },
  { name: 'Abdominales (crunch)', category: 'isolation', muscle_groups: ['Core'], equipment: ['Peso corporal'] },
  { name: 'Abdominales en polea', category: 'isolation', muscle_groups: ['Core'], equipment: ['Cable'] },
  { name: 'Elevación de piernas colgado', category: 'isolation', muscle_groups: ['Core'], equipment: ['Peso corporal'] },
  { name: 'Elevación de rodillas colgado', category: 'isolation', muscle_groups: ['Core'], equipment: ['Peso corporal'] },
  { name: 'Rueda abdominal', category: 'isolation', muscle_groups: ['Core'], equipment: ['Peso corporal'] },
  { name: 'Russian twist', category: 'isolation', muscle_groups: ['Core'], equipment: ['Peso corporal'] },
  { name: 'Abdominales en máquina', category: 'isolation', muscle_groups: ['Core'], equipment: ['Máquina'] },
  { name: 'Escaladores (mountain climbers)', category: 'isolation', muscle_groups: ['Core'], equipment: ['Peso corporal'] },
  { name: 'Elevación de talones de pie', category: 'isolation', muscle_groups: ['Pantorrillas'], equipment: ['Máquina'] },
  { name: 'Elevación de talones sentado', category: 'isolation', muscle_groups: ['Pantorrillas'], equipment: ['Máquina'] },
  { name: 'Elevación de talones en prensa', category: 'isolation', muscle_groups: ['Pantorrillas'], equipment: ['Máquina'] },
  { name: 'Curl de muñeca', category: 'isolation', muscle_groups: ['Antebrazos'], equipment: ['Barra'] },
  { name: 'Curl de muñeca inverso', category: 'isolation', muscle_groups: ['Antebrazos'], equipment: ['Barra'] },
  { name: "Farmer's walk", category: 'compound', muscle_groups: ['Antebrazos', 'Core'], equipment: ['Mancuerna'] },
  { name: 'Cinta de correr', category: 'cardio', muscle_groups: ['Piernas'], equipment: ['Máquina'] },
  { name: 'Bicicleta estática', category: 'cardio', muscle_groups: ['Piernas'], equipment: ['Máquina'] },
  { name: 'Elíptica', category: 'cardio', muscle_groups: ['Piernas'], equipment: ['Máquina'] },
  { name: 'Máquina de remo', category: 'cardio', muscle_groups: ['Espalda', 'Piernas'], equipment: ['Máquina'] },
  { name: 'Escalador (stair climber)', category: 'cardio', muscle_groups: ['Piernas', 'Glúteos'], equipment: ['Máquina'] },
  { name: 'Comba (cuerda de saltar)', category: 'cardio', muscle_groups: ['Piernas', 'Pantorrillas'], equipment: ['Peso corporal'] },
  { name: 'Natación', category: 'cardio', muscle_groups: ['Espalda', 'Hombros', 'Piernas'], equipment: ['Peso corporal'] },
  { name: 'Carrera al aire libre', category: 'cardio', muscle_groups: ['Piernas'], equipment: ['Peso corporal'] },
  { name: 'Bicicleta al aire libre', category: 'cardio', muscle_groups: ['Piernas'], equipment: ['Peso corporal'] },
  { name: 'Burpees', category: 'cardio', muscle_groups: ['Piernas', 'Pecho', 'Core'], equipment: ['Peso corporal'] },
];
